[package]
name = "chemrust-kpoint-gen"
description.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
chemrust-geometry = { path = "../chemrust-geometry" }
crystallographic-group = { version = "0.3.1" }
nalgebra = { version = "0.33.2", features = ["compare", "debug"] }
