[package]
name = "chemrust-geometry"
edition.workspace = true
version = "0.1.0"
authors.workspace = true
description = "Crystal geometry toolkit for computational materials science — Structure, lattice vectors, transforms, and slab generation."
license.workspace = true

[dependencies]
nalgebra = {version="0.33", features=["debug", "compare"]}
castep-periodic-table = "0.5.2"
crystallographic-group = "0.3.1"

[dev-dependencies]
castep-cell-io = { path = "../../castep-cell-io/castep_cell_io" }
castep-cell-fmt = { path = "../../castep-cell-io/castep_cell_fmt" }
anyhow = "1"
