[package]
name = "chemrust-core"
edition.workspace = true
version = "0.3.0"
authors.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version="0.*", features=["debug", "compare"]}
castep-periodic-table = "0.3"
nom = "7.1.3"
num = "0.4.1"
itertools = "0.12.1"
