[package]
name = "chemrust-core"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version="0.*", features=["debug", "compare", "rand","macros", "alloc", "arbitrary"]}
castep-periodic-table = "0.2.2"
nom = "7.1.3"
num = "0.4.1"
itertools = "0.12.1"
crystallographic-group = "0.1"
# rayon = "1.*"
# glob = "0"
